### ISSUE TITLE
Comments in exports misaligned

### ISSUE THREAD

**Issue by jml** [commercialhaskell/hindent#220]
I just ran `hindent` on https://github.com/jml/difftodo/blob/master/src/Fixme.hs#L5-L14 which produces this diff:

``` diff
index 647b27e..c92f30c 100644
--- a/src/Fixme.hs
+++ b/src/Fixme.hs
@@ -1,17 +1,16 @@
 -- | Routines for getting todos from source code
 --
 -- No backwards compatibility is promised for any code in this library.
-
 module Fixme
-  ( -- | Get comments from code or from diffs
-    Comment.parseComments
+-- | Get comments from code or from diffs
+  ( Comment.parseComments
   , Diff.newCommentsFromDiff
   , Comment.readComments
-    -- | Turn comments into todos
+   -- | Turn comments into todos
   , Todo.getTodos
-    -- | Format todos
-  , Todo.formatTodo
-  ) where
+   -- | Format todos
+  , Todo.formatTodo)
+  where
```

Note that the comments are de-dented by 1 space.

The [style guide](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md#export-lists) says they should be aligned with symbol names. i.e. that that chunk of code should not be changed by hindent.

Really love the direction hindent is going in. Thanks!

**Comment by jml** [comment]
Also, the first comment seems to go flush with 0 column. Not sure whether that's deliberate or a bug, but suspect the latter.

**Comment by chrisdone** [comment]
I think that I might have to implement a bit of special logic for export lists to handle comments properly. :+1:

---

**Explanation**

There are multiple passes for comment association here: https://github.com/chrisdone/hindent/blob/master/src/HIndent.hs#L338

As the semantics of export comments is "this comment is for the line below", like for haddocks before decls, so that kind of logic will need to be added. Currently what we're seeing is the "this comment comes after the thing it's about" applied to the export list and the result is not good.

> Also, the first comment seems to go flush with 0 column.

So with my explanation in mind; that explains this result: hindent currently thinks the comment is for `Fixme`. I think specifically [this pass](https://github.com/chrisdone/hindent/blob/master/src/HIndent.hs#L344) is picking up that comment.

**Comment by qua-bla** [comment]
This problem with the first comment also appears for records.

Example from haddock documentation

```hs
data R a b =
  C { -- | This is the documentation for the 'a' field
      a :: a,
      -- | This is the documentation for the 'b' field
      b :: b
    }
```

becomes

```hs
data R a b = C -- | This is the documentation for the 'a' field
  { a :: a
    -- | This is the documentation for the 'b' field
  , b :: b
  }
```

Note, that haddock would assign comments correctly when using

```hs
data R a b = C
  { -- | This is the documentation for the 'a' field
    a :: a
    -- | This is the documentation for the 'b' field
  , b :: b
  }
```

**Comment by sighingnow** [comment]
Another case to re-produce this problem:

~~~haskell
f x =
  case x of
    -- True
    True -> 1
    -- False
    False -> 2
~~~

becomes

~~~haskell
f :: Bool -> Int
f x =
  case x
       -- True
        of
    True -> 1
    -- False
    False -> 2
~~~

**Comment by chrisdone** [comment]
Closing in favor of #511.
