### ISSUE TITLE
top-level pragmas break two lines

### ISSUE THREAD

**Issue by sgraf812** [commercialhaskell/hindent#255]
Relevant example: http://tinyurl.com/jkhyhs5

```
{-# NOINLINE sayHi #-}

sayHi = unsafePerformIO (putStrLn "hi")
```

I don't think I like that. The [style guide](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md#pragmas) recommends to put pragmas after the definition, but then it gets formatted as

```
sayHi = unsafePerformIO (putStrLn "hi")

{-# NOINLINE sayHi #-}
```

regardless (http://tinyurl.com/hkq6a3p)

**Comment by chrisdone** [comment]
Agreed, it's because a pragma is a proper declaration, I think. Not a comment per se. So we just need a special case in the printer to omit the newline before such a pragma. Should be here: https://github.com/chrisdone/hindent/blob/master/src/HIndent/Pretty.hs#L1066 If you want to tackle it. Add a case for `InlineSig`.

**Comment by sgraf812** [comment]
Thanks for the pointer! Implementing the first version (pragmas before decl) was trivial, however the second (pragmas after decl) wouldn't be so easy, because individual decls can only add newlines after them. I prefer the first version anyway (feels like a type signature), but the second is suggested by the style guide. What do you think?

Also: Wouldn't it be reasonable to have a fork of the style guide in the long term? I think tibbe's is a good baseline, but some choices should be disputed, others should be made to begin with.

**Comment by chrisdone** [comment]
Looks like this was implemented.
