### ISSUE TITLE
type signatures with the identifier and the :: on different lines breaks textmate grammars 

### ISSUE THREAD

**Issue by duog** [commercialhaskell/hindent#284]
the signature:

``` haskell
foo :: (MonadState Int m, MonadReader Int m, MonadMask m, MonadFix m) => a -> m ()
```

is reformatted to:

``` haskell
foo
  :: (MonadState Int m, MonadReader Int m, MonadMask m, MonadFix m)
```

This breaks syntax highlighting on atom, and I would assume on other text editors using textmate grammars. 

Would it be possible for the style to be modified to linebreak after the :: ?

**Comment by chrisdone** [comment]
Possibly, we've been discussing doing that also for greppability. We're not sure how best to format it, though.

**Comment by tfausak** [comment]
For what it's worth, I prefer the newline before `::`. The real problem here is the TextMate grammar. Atom uses the same grammar. The language-haskell Atom package hit this problem (https://github.com/atom-haskell/language-haskell/issues/59): 

> Long story short, this is impossible to highlight with Atom's syntax model, since it parses one line at a time and backtracking is not allowed.

Even if `::` was on the same line, there are other problems:

- https://github.com/atom-haskell/language-haskell/issues/81
- https://github.com/atom-haskell/language-haskell/issues/67
- https://github.com/atom-haskell/language-haskell/issues/57

**Comment by duog** [comment]
My understanding is that the real problem is the TextMate grammar spec, in that this problem is not solvable by fixing the grammar.
 
Those other problems exist, but this change would make the highlighting behave much better.

For reference, here is a screenshot of how the atom syntax highlights some examples:
![selection_001](https://cloud.githubusercontent.com/assets/3441949/18257228/7eab99e4-7414-11e6-86a6-47ac4c90abd6.png)

gist here: https://gist.github.com/duog/7ed1332ef6f5bddda62a6cdf72e885a6
