### ISSUE TITLE
cannot parse imported pattern synonyms

### ISSUE THREAD

**Issue by cdepillabout** [commercialhaskell/hindent#398]
I get an error when trying to format [imported pattern synonyms](https://downloads.haskell.org/~ghc/8.0.1/docs/html/users_guide/glasgow_exts.html#import-and-export-of-pattern-synonyms).

Here is an example of a (legal) import statement that produces an error:

```haskell
{-# LANGUAGE PatternSynonyms #-}

import Foo (pattern Bar)
```

**Comment by sighingnow** [comment]
You should use `-X` to enable `PatternSynonyms` extension explicitly. Please try the following command line:

~~~shell
cat <your-file> | hindent -XPatternSynonyms
~~~

**Comment by cdepillabout** [comment]
Thanks for the information!

Is there a reason why `PatternSynonyms` has to be enabled explicitly, but most extensions do not?

Also, is there a good way to use `hindent` from Vim and always enable `PatternSynonyms`?  The README.md doesn't mention it.

**Comment by sighingnow** [comment]
Almost all [known extensions](http://hackage.haskell.org/package/haskell-src-exts-1.19.1/docs/Language-Haskell-Exts-Extension.html#t:KnownExtension) are enabled by default, except some which are marked as `badExtension` because they steal complicate syntax. The whole list of bad extensions are listed here: [badExtensions](https://github.com/commercialhaskell/hindent/blob/master/src/HIndent.hs#L272).

Currently, enable an extension can only be done via command line arguments. Maybe we will support enabling extensions via the `.hindent.yaml` configuration file.

As for vim, it's up to how you integrate hindent with vim. For example, the following command works well for me.

~~~
:%!hindent -XPatternSynonyms
~~~

**Comment by cdepillabout** [comment]
> Maybe we will support enabling extensions via the `.hindent.yaml` configuration file.

I think this might be a good idea.  I have `PatternSynonyms` turned on in the cabal file for all Haskell files in our application.  It would be nice to be able to enable it in the `.hindent.yaml` file so that other programmers don't have to worry about it.

I currently have `hindent` set as the `formatprg` in Vim, so I'll have to play around with it to figure out how to get it working.

**Comment by sighingnow** [comment]
Please try

~~~
setlocal formatprg=hindent\ -XPatternSynonyms
~~~

**Comment by cdepillabout** [comment]
Thanks, I'll try that out!

**Comment by sighingnow** [comment]
Close as fixed.
